export const employeeActionTypes = {
    GET_ALL_EMPLOYEE_START: 'GET_ALL_EMPLOYEE_START',
    GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
    GET_ALL_EMPLOYEE_FAILURE: 'GET_ALL_EMPLOYEE_FAILURE',

    CREATE_EMPLOYEE_START: 'CREATE_EMPLOYEE_START',
    CREATE_EMPLOYEE_SUCCESS: 'CREATE_EMPLOYEE_SUCCESS',
    CREATE_EMPLOYEE_FAILURE: 'CREATE_EMPLOYEE_FAILURE',

    UPDATE_EMPLOYEE_START: 'UPDATE_EMPLOYEE_START',
    UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
    UPDATE_EMPLOYEE_FAILURE: 'UPDATE_EMPLOYEE_FAILURE',

    DELETE_EMPLOYEE_START: 'DELETE_EMPLOYEE_START',
    DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_FAILURE: 'DELETE_EMPLOYEE_FAILURE',
    
    REMOVE_MESSAGE: 'REMOVE_MESSAGE'
}