version: '3.8'
services: 
    server-api:
      build: ./server
      restart: unless-stopped
      ports:
        - 5000:5000
      hostname: backend
      networks:
        - app-network
    client-ui:
      depends_on:
        - server-api
      build:
        context: ./client
      ports:
        - 3000:80
      hostname: frontend
      networks:
        - app-network  
    # nginx:
    #   restart: always
    #   depends_on:
    #      - server-api
    #      - client-ui
    #   build:
    #      context: ./nginx
    #   ports:
    #      - 8080:80
    #   networks:
    #      - app-network
networks:
  app-network:
    driver: bridge